# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [5]:
import numpy as np
arr = np.random.uniform(0, 21, size = (4,7)).round(3)
min_val = arr.min()
max_val = arr.max()
a = 1/(max_val-min_val)
b = -a * min_val
ans = a*arr+b
ans

array([[0.79990246, 1.        , 0.73942941, 0.73708851, 0.67373811,
        0.77117776, 0.70534016],
       [0.52162887, 0.60409656, 0.8405267 , 0.97229944, 0.9267008 ,
        0.53182151, 0.96620337],
       [0.10870519, 0.85740063, 0.57854182, 0.79141673, 0.9931724 ,
        0.11558157, 0.94415996],
       [0.38405267, 0.017703  , 0.28710071, 0.58517435, 0.        ,
        0.95176786, 0.85886369]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [8]:
arr = np.random.randint(0, 11, (8,10))
index = np.argmin(np.sum(arr, axis = 1))
arr,arr[index]

(array([[ 3, 10,  4, 10,  5,  5,  4,  6,  4,  2],
        [ 0, 10,  7,  7,  0,  0,  7,  7,  3,  9],
        [ 9,  0,  4,  9,  9,  6,  0,  1,  9,  1],
        [ 4,  3,  9,  2, 10,  6,  0,  6,  5,  2],
        [ 0,  6,  5,  5,  2,  8,  5,  5,  2,  6],
        [ 2,  2,  2,  7,  0, 10,  1,  7, 10,  0],
        [ 1,  3,  0,  8,  6,  7,  5, 10,  8,  9],
        [ 8,  8,  5,  1,  7,  9,  8,  6,  0,  2]]),
 array([ 2,  2,  2,  7,  0, 10,  1,  7, 10,  0]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [9]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([5, 4, 3, 2, 1])

ans = np.linalg.norm(vector1 - vector2)
ans

6.324555320336759

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [10]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
A_1 = np.linalg.inv(A)
B_1 = np.linalg.inv(B)
C_1 = -1*C
A_1 @ C_1 @ B_1

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [77]:
data = np.loadtxt('minutes_n_ingredients.csv',delimiter=',',dtype=np.int32,skiprows=1)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [28]:
minutes_min = np.min(data[:,1])
minutes_max = np.max(data[:,1])
median_first = np.median(data[:,1])
average_first = np.mean(data[:,1])
print('Минимальный для 2 столбца:', minutes_min)
print('Максимальный для 2 столбца:', minutes_max)
print('Медиана для 2 столбца:', median_first)
print('Среднее для 2 столбца:', average_first)
ing_min = np.min(data[:,2])
ing_max = np.max(data[:,2])
median_second = np.median(data[:,2])
average_second = np.mean(data[:,2])
print('Минимальный для 3 столбца:', ing_min)
print('Максимальный для 3 столбца:', ing_max)
print('Медиана для 3 столбца:', median_second)
print('Среднее для 3 столбца:', average_second)

Минимальный для 2 столбца: 0
Максимальный для 2 столбца: 2147483647
Медиана для 2 столбца: 40.0
Среднее для 2 столбца: 21601.00169
Минимальный для 3 столбца: 1
Максимальный для 3 столбца: 39
Медиана для 3 столбца: 9.0
Среднее для 3 столбца: 9.05528


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [32]:
quantile_value = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.minimum(data[:, 1], quantile_value)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [78]:
print(np.count_nonzero(data[:, 1] == 0))
data[:,1][data[:,1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [79]:
np.unique(data[:,0]).size

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [84]:
unique_ing = np.unique(data[:,2])
print(unique_ing.size)
print(unique_ing)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [86]:
data[data[:,2]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [100]:
average_ing = data[:, 2] / data[:, 1]
np.max(average_ing)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [99]:
np.mean(np.sort(data[:,2])[::-1][:100])

28.22

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [134]:
np.random.default_rng().choice(data, 10)

array([[417903,     75,      6],
       [117802,     15,      9],
       [ 76244,     25,      6],
       [122767,    140,     12],
       [433508,     55,     10],
       [136111,     25,      4],
       [267210,    150,      6],
       [139797,     20,      9],
       [ 19270,     45,     11],
       [173964,     15,      8]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [135]:
np.mean(data[:,2]<np.mean(data[:,2]))*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [143]:
simple = (data[:,1]<=20) & (data[:,2]<=5)
simple_data = np.column_stack((data,simple))

13. Выведите процент "простых" рецептов в датасете

In [182]:
np.mean(simple_data[:,3]==1)*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [315]:
short = np.column_stack((np.full((data[data[:,1]<=10][:,0].size,1),0),data[data[:,1]<=10]))
standart = np.column_stack((np.full((data[(data[:,1]>10) &(data[:,1]<20)][:,0].size,1),1),data[(data[:,1]>10) &(data[:,1]<20)]))
long = np.column_stack((np.full((data[data[:,1]>=20][:,0].size,1),2),data[data[:,1]>=20]))
new_data = np.ndarray((3, np.max([short[:,0].size, standart[:,0].size, long[:,0].size]), 2))
new_data[0, :short[:,0].size] = short[:,2:4]
new_data[1, :standart[:,0].size] = standart[:,2:4]
new_data[2, :long[:,0].size] = long[:,2:4]
new_data.shape


(3, 79751, 2)